window.Solaris = window.Solaris || {};

(function (Solaris) {
  'use strict';

  Solaris.PLANTAS_LOCAIS = [
    // Horta e Ervas (1 a 20)
    { id: 1, nome: "Tomate cereja", especie: "Solanum lycopersicum", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/tomate-cereja.jpg" },
    { id: 2, nome: "Manjericão", especie: "Ocimum basilicum", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 3, nome: "Alecrim", especie: "Salvia rosmarinus", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 4, nome: "Hortelã", especie: "Mentha", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 5, nome: "Salsinha", especie: "Petroselinum crispum", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 6, nome: "Cebolinha", especie: "Allium fistulosum", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 7, nome: "Orégano", especie: "Origanum vulgare", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 8, nome: "Tomilho", especie: "Thymus vulgaris", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 9, nome: "Coentro", especie: "Coriandrum sativum", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 10, nome: "Alface Crespa", especie: "Lactuca sativa", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 11, nome: "Rúcula", especie: "Eruca vesicaria", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 12, nome: "Espinafre", especie: "Spinacia oleracea", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 13, nome: "Cenoura", especie: "Daucus carota", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 14, nome: "Rabanete", especie: "Raphanus sativus", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 15, nome: "Beterraba", especie: "Beta vulgaris", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 16, nome: "Pimenta Malagueta", especie: "Capsicum frutescens", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 17, nome: "Pimentão", especie: "Capsicum annuum", luz: "Sol pleno", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 18, nome: "Morango", especie: "Fragaria", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 19, nome: "Couve-manteiga", especie: "Brassica oleracea", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 20, nome: "Sálvia", especie: "Salvia officinalis", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },

    // Plantas de Interior (21 a 45)
    { id: 21, nome: "Jiboia", especie: "Epipremnum ureum", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/jiboia.jpg" },
    { id: 22, nome: "Espada-de-São-Jorge", especie: "Sansevieria trifasciata", luz: "Luz indireta", dificuldade: "Muito Fácil", foto: "assets/images/espada.jpg" },
    { id: 23, nome: "Zamioculca", especie: "Zamioculcas zamiifolia", luz: "Luz indireta", dificuldade: "Muito Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 24, nome: "Costela-de-Adão", especie: "Monstera deliciosa", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 25, nome: "Lírio-da-paz", especie: "Spathiphyllum wallisii", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 26, nome: "Ficus lyrata", especie: "Ficus lyrata", luz: "Meia-sombra", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 27, nome: "Antúrio", especie: "Anthurium andraeanum", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 28, nome: "Comigo-ninguém-pode", especie: "Dieffenbachia seguine", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 29, nome: "Singônio", especie: "Syngonium podophyllum", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 30, nome: "Peperômia", especie: "Peperomia caperata", luz: "Luz indireta", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 31, nome: "Maranta-pavão", especie: "Calathea makoyana", luz: "Luz indireta", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 32, nome: "Filodendro-brasil", especie: "Philodendron hederaceum", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 33, nome: "Begônia-maculata", especie: "Begonia maculata", luz: "Luz indireta", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 34, nome: "Alocásia-polly", especie: "Alocasia amazonica", luz: "Meia-sombra", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 35, nome: "Asplênio", especie: "Asplenium nidus", luz: "Luz indireta", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 36, nome: "Samambaia-americana", especie: "Nephrolepis exaltata", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 37, nome: "Avenca", especie: "Adiantum capillus-veneris", luz: "Luz indireta", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 38, nome: "Caládio", especie: "Caladium bicolor", luz: "Meia-sombra", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 39, nome: "Clorofito", especie: "Chlorophytum comosum", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 40, nome: "Bambu-da-sorte", especie: "Dracaena sanderiana", luz: "Luz indireta", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 41, nome: "Pata-de-elefante", especie: "Beaucarnea recurvata", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 42, nome: "Árvore-da-felicidade", especie: "Polyscias fruticosa", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 43, nome: "Palmeira-rápis", especie: "Rhapis excelsa", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 44, nome: "Dracena-de-Madagascar", especie: "Dracaena marginata", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 45, nome: "Fitônia", especie: "Fittonia albivenis", luz: "Luz indireta", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },

    // Suculentas e Cactos (46 a 70)
    { id: 46, nome: "Babosa (Aloe Vera)", especie: "Aloe barbadensis", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 47, nome: "Echeveria", especie: "Echeveria elegans", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 48, nome: "Planta-jade", especie: "Crassula ovata", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 49, nome: "Cacto-amendoim", especie: "Echinopsis chamaecereus", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 50, nome: "Coroa-de-frades", especie: "Melocactus", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 51, nome: "Rabo-de-burro", especie: "Sedum morganianum", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 52, nome: "Orelha-de-Shrek", especie: "Crassula ovata 'Gollum'", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 53, nome: "Colar-de-pérolas", especie: "Senecio rowleyanus", luz: "Meia-sombra", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 54, nome: "Flor-de-maio", especie: "Schlumbergera truncata", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 55, nome: "Cacto-macarrão", especie: "Rhipsalis baccifera", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 56, nome: "Rosa-de-pedra", especie: "Graptopetalum paraguayense", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 57, nome: "Kalanchoe", especie: "Kalanchoe blossfeldiana", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 58, nome: "Coração-emaranhado", especie: "Ceropegia woodii", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 59, nome: "Haworthia", especie: "Haworthia fasciata", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 60, nome: "Avelós", especie: "Euphorbia tirucalli", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 61, nome: "Cacto-mandacaru", especie: "Cereus jamacaru", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 62, nome: "Cacto-saguaro", especie: "Carnegiea gigantea", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 63, nome: "Dedo-de-moça", especie: "Sedum pachyphyllum", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 64, nome: "Agave", especie: "Agave americana", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 65, nome: "Coroa-de-cristo", especie: "Euphorbia milii", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 66, nome: "Planta-fantasma", especie: "Graptopetalum paraguayense", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 67, nome: "Cacto-bola", especie: "Parodia magnifica", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 68, nome: "Colar-de-rubi", especie: "Othonna capensis", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 69, nome: "Cacto-estrela", especie: "Stapelia hirsuta", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 70, nome: "Gasteria", especie: "Gasteria spp.", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },

    // Flores e Ornamentais (71 a 90)
    { id: 71, nome: "Girassol", especie: "Helianthus annuus", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 72, nome: "Rosa Vermelha", especie: "Rosa gallica", luz: "Sol pleno", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 73, nome: "Orquídea Phalaenopsis", especie: "Phalaenopsis aphrodite", luz: "Luz indireta", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 74, nome: "Violeta", especie: "Saintpaulia ionantha", luz: "Luz indireta", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 75, nome: "Margarida", especie: "Leucanthemum vulgare", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 76, nome: "Hibisco", especie: "Hibiscus rosa-sinensis", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 77, nome: "Azaleia", especie: "Rhododendron simsii", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 78, nome: "Hortênsia", especie: "Hydrangea macrophylla", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 79, nome: "Copo-de-leite", especie: "Zantedeschia aethiopica", luz: "Meia-sombra", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 80, nome: "Tulipa", especie: "Tulipa gesneriana", luz: "Sol pleno", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 81, nome: "Boca-de-leão", especie: "Antirrhinum majus", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 82, nome: "Primavera (Bougainvillea)", especie: "Bougainvillea glabra", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 83, nome: "Onze-horas", especie: "Portulaca grandiflora", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 84, nome: "Jasmim", especie: "Jasminum officinale", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 85, nome: "Lavanda", especie: "Lavandula angustifolia", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 86, nome: "Camélia", especie: "Camellia japonica", luz: "Meia-sombra", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 87, nome: "Amor-perfeito", especie: "Viola tricolor", luz: "Meia-sombra", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" },
    { id: 88, nome: "Cravo", especie: "Dianthus caryophyllus", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 89, nome: "Gérbera", especie: "Gerbera jamesonii", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 90, nome: "Crisântemo", especie: "Chrysanthemum", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },

    // Frutíferas em Vaso / Diversas (91 a 100)
    { id: 91, nome: "Limoeiro Siciliano", especie: "Citrus limon", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 92, nome: "Jabuticabeira", especie: "Plinia cauliflora", luz: "Sol pleno", dificuldade: "Difícil", foto: "assets/images/placeholder.jpg" },
    { id: 93, nome: "Pitangueira", especie: "Eugenia uniflora", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 94, nome: "Pé de Amora", especie: "Morus nigra", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 95, nome: "Acerola", especie: "Malpighia emarginata", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 96, nome: "Romã", especie: "Punica granatum", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 97, nome: "Figueira", especie: "Ficus carica", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 98, nome: "Maracujá", especie: "Passiflora edulis", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 99, nome: "Goiabeira", especie: "Psidium guajava", luz: "Sol pleno", dificuldade: "Média", foto: "assets/images/placeholder.jpg" },
    { id: 100, nome: "Araçá", especie: "Psidium cattleianum", luz: "Sol pleno", dificuldade: "Fácil", foto: "assets/images/placeholder.jpg" }
  ];
})(window.Solaris);
